### ISSUE TITLE
[Bug]: Snyk is failing due to dependency vulnerabilities

### ISSUE THREAD

**Issue by AnnaDodson** [dvsa/dvsa-lambda-logger#1]
### What happened?

Current dependencies are failing Snyk dependency scans. Need updating.

### Relevant log output

```shell
See logs here: https://github.com/dvsa/dvsa-lambda-logger/actions/runs/1398536895
```

**Comment by sdh100shaun** [comment]
This was due to the token scope - amended at organisation level
